!-----------------------------------------------------------------------
!> @brief
!> Local data storage (inside each processor)
!-----------------------------------------------------------------------

MODULE LOCAL_STORAGE

USE MPI

IMPLICIT NONE 

INTEGER :: LOCAL_ELEM_NUM   !< LOCAL ELEMENT NUMBER, START WITH 1

INTEGER :: ORIGINAL_ELEM_NUM    !< ELEMNT NUMBER BEFORE ADAPT, START WITH 1

INTEGER, ALLOCATABLE, DIMENSION(:) :: A_LEVEL    !< ELEMENT ADAPT LEVEL, ROOT ELEMENT LEVEL = 0

INTEGER, ALLOCATABLE, DIMENSION(:) :: PLEVEL_X     !< POLYNOMIAL LEVEL IN X(CAN BE TRANSFORM TO POLY ORDER), START WITH 1
INTEGER, ALLOCATABLE, DIMENSION(:) :: PLEVEL_Y     !< POLYNOMIAL LEVEL IN Y(CAN BE TRANSFORM TO POLY ORDER)

INTEGER, ALLOCATABLE, DIMENSION(:) :: ELEM_RANGE    !< ELEMENT STORAGE RANGE IN EACH PROCESSOR, USE THE LAST ELEMENT NUMBER TO REPRESENT, START WITH 0

INTEGER, ALLOCATABLE, DIMENSION(:, :, :) :: GHOST_LEVEL !< THE POLYNOMIAL ORDER OF THE NEIGHT

DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: X_LOCAL   !< X COORDINATES, START WITH ELEM 0
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: Y_LOCAL   !< Y COORDINATES

DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :, :) :: GHOST_FACES_X   !< TWO GHOST FACES IN X DIRECTION FOR MPI INTERFACES FLUXES EXCHANGE
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :, :) :: GHOST_FACES_Y   !< TWO GHOST FACES IN Y DIRECTION FOR MPI INTERFACES FLUXES EXCHANGE


DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :, :) :: SOLUTION   !< SOLUTION(PRESSURE, VELOCITIES IN TWO DIRECTION)


END MODULE LOCAL_STORAGE
