!-----------------------------------------------------------------------
!> @brief
!> Local data storage (inside each processor)
!-----------------------------------------------------------------------

MODULE LOCAL_STORAGE

USE MPI

IMPLICIT NONE 

INTEGER :: LOCAL_ELEM_NUM   !< LOCAL ELEMENT NUMBER, START WITH 1

INTEGER :: ORIGINAL_ELEM_NUM    !< ELEMNT NUMBER BEFORE ADAPT, START WITH 1

INTEGER :: WIN_INTERFACE_L !< WINDOW OBJECT FOR ELEMENT INTERFACES
INTEGER :: WIN_INTERFACE_R !< WINDOW OBJECT FOR ELEMENT INTERFACES

INTEGER :: WIN_NFLUX_L !< WINDOW OBJECT FOR ELEMENT NUMERICAL FLUXES
INTEGER :: WIN_NFLUX_R !< WINDOW OBJECT FOR ELEMENT NUMERICAL FLUXES

INTEGER, ALLOCATABLE, DIMENSION(:) :: A_LEVEL    !< ELEMENT ADAPT LEVEL, ROOT ELEMENT LEVEL = 0

INTEGER, ALLOCATABLE, DIMENSION(:) :: PLEVEL_X     !< POLYNOMIAL LEVEL IN X(CAN BE TRANSFORM TO POLY ORDER), START WITH 1
INTEGER, ALLOCATABLE, DIMENSION(:) :: PLEVEL_Y     !< POLYNOMIAL LEVEL IN Y(CAN BE TRANSFORM TO POLY ORDER)

INTEGER, ALLOCATABLE, DIMENSION(:) :: ELEM_RANGE    !< ELEMENT STORAGE RANGE IN EACH PROCESSOR, USE THE LAST ELEMENT NUMBER TO REPRESENT, START WITH 0 (GLOBAL INDEX)

INTEGER, ALLOCATABLE, DIMENSION(:, :, :) :: GHOST_LEVEL !< THE POLYNOMIAL ORDER OF THE NEIGHT

DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: X_LOCAL   !< X COORDINATES, START WITH ELEM 0
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: Y_LOCAL   !< Y COORDINATES

DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :, :) :: SOLUTION   !< SOLUTION(PRESSURE, VELOCITIES IN TWO DIRECTION)

DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: SOLUTION_INT_L   !< INTERIOR SOLUTION AT LEFT BOUNDARY
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: SOLUTION_INT_R   !< INTERIOR SOLUTION AT RIGHT BOUNDARY


DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: NFLUX_X_L !< NUMERICAL FLUX AT LEFT BOUNDARY
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: NFLUX_X_R !< NUMERICAL FLUX AT RIGHT BOUNDARY 
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: NFLUX_Y_D !< NUMERICAL FLUX AT BOTTOM  
DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :, :) :: NFLUX_Y_U !< NUMERICAL FLUX AT TOP 


LOGICAL, ALLOCATABLE, DIMENSION(:, :) :: MPI_B_FLAG   !< MPI BOUNDARY FLAG (ON FOUR SIDES OF AN ELEMENT). .TRUE. == ON THE MPI_BOUNDARY

END MODULE LOCAL_STORAGE
