!-----------------------------------------------------------------------
!> @brief
!> 1. Read the .msh file generated by GMSH. 
!! 2. Sort the local element node numbering sequence. 
!! 3. Generate dual graph of the mesh. 
!! 4. Re-numbering all the elements by using Hilbert curve.
!-----------------------------------------------------------------------

MODULE PREPARE_HILBERT_SCHEME

USE MPI
USE READ_MESH
USE GEN_DUAL_GRAPH
USE HILBERT_SORT
USE PARAM, ONLY: RANK

IMPLICIT NONE

CONTAINS

SUBROUTINE HILBERT_NUMBERING
    
    IMPLICIT NONE
    
    ! ONLY PROC1 READ THE MESH------------------------------------------
    IF (RANK == 0) THEN
        
        ! READ MESH FILE------------------------------------------------
        CALL READ_MESH_2D
        !---------------------------------------------------------------
        
        ! GENERATE DUAL GRAPH-------------------------------------------
        CALL GEN_DUAL_GRAPH_2D
        !---------------------------------------------------------------
        
        ! RE-NUMBERING ELEMENT BY HILBERT CURVE-------------------------
        CALL HIBERT_SORT_2D
        !---------------------------------------------------------------
    
    ENDIF
    !-------------------------------------------------------------------
    
    ! DISTRIBUTE THE ELEMENTS EVENLY BETWEEN PROCESSORS-----------------
    
    !-------------------------------------------------------------------
    
END SUBROUTINE HILBERT_NUMBERING

END MODULE PREPARE_HILBERT_SCHEME
